var DB = require("./connection");

var bcrypt = require('bcryptjs');

DB.models.User.create({twitter_id: 0})
.done(function(){DB.models.Pin.create({title: "London, UK", latitude: 51.5072, longitude: -0.1275, userId: 1, isRed: "t", description: "This was my wondeful trip to the UK. It was amazing in every way. The end."})
.done(function(){DB.models.Photo.create({photoUrl: "http://d185ox70mr1pkc.cloudfront.net/post_image/london.jpg", pinId: 1})
.done(function(){DB.models.Photo.create({photoUrl: "http://collections.uiowa.edu/web-images/internationalPrograms/ofsa/3026/application/Ben%20Ben%20Bus%20London.jpg", pinId: 1})
.done(function(){DB.models.Photo.create({photoUrl: "http://cdni.wired.co.uk/1920x1280/k_n/London_5.jpg", pinId: 1})
.done(function(){DB.models.Photo.create({photoUrl: "http://37.128.132.134/~hstudio/content/uploads/2013/02/nbfl.4.jpg", pinId: 1})
.done(function(){DB.models.Photo.create({photoUrl: "http://cdn.londonandpartners.com/visit/london-organisations/the-shard/65734-640x360-skyline-shard-640.jpg", pinId: 1})
.done(function(){DB.models.Pin.create({title: "Beijing", latitude: 39.9167, longitude: 116.3833, userId: 1, isRed: "t", description: "Yay Beijing"})
.done(function(){DB.models.Photo.create({photoUrl: "http://destinations.flysaa.com/photos/beijing2.jpg", pinId: 2})
.done(function(){DB.models.Photo.create({photoUrl: "http://cdni.wired.co.uk/620x413/s_v/shutterstock_111796310.jpg", pinId: 2})
.done(function(){DB.models.Photo.create({photoUrl: "http://www.telegraph.co.uk/travel/destination/china/article119715.ece/ALTERNATES/w620/beijing-forbidden-city-use.jpg", pinId: 2})
.done(function(){DB.models.Photo.create({photoUrl: "http://cdn.homesthetics.net/wp-content/uploads/2013/10/The-Chinese-National-Stadium-in-Beijing-%E2%80%93-The-Bird%E2%80%99s-Nest-Stadium-homesthetics-5.jpg", pinId: 2})
.done(function(){DB.models.Pin.create({title: "Rio De Janeiro", latitude: -22.9068, longitude: -43.1729, userId: 1, isRed: "t", description: "Yay Rio"})
.done(function(){DB.models.Photo.create({photoUrl: "http://www.hotelroomsearch.net/im/2014/11/rio-de-janeiro-3.jpg", pinId: 3})
.done(function(){DB.models.Photo.create({photoUrl: "http://cache-graphicslib.viator.com/graphicslib/thumbs674x446/2484/SITours/corcovado-mountain-christ-redeemer-and-sugar-loaf-mountain-day-tour-in-rio-de-janeiro-121548.jpg", pinId: 3})
.done(function(){DB.models.Photo.create({photoUrl: "https://www.irisglobal.org/images/harvest/river-of-god/rio-de-janeiro.jpg", pinId: 3})
.done(function(){DB.models.Photo.create({photoUrl: "http://i.telegraph.co.uk/multimedia/archive/02587/verde-beach_2587444b.jpg", pinId: 3})
.done(function(){DB.models.Photo.create({photoUrl: "http://images.nationalgeographic.com/wpf/media-live/photos/000/698/cache/beach-rio-de-janeiro-harvey_69843_990x742.jpg", pinId: 3})
.done(function(){DB.models.Pin.create({title: "Maui", latitude: 20.8000, longitude: -156.3333, userId: 1, isRed: "t", description: "Yay Maui"})
.done(function(){DB.models.Photo.create({photoUrl: "http://tiger.towson.edu/~bhamm2/kaanapali-beach_maui_hawaii.jpg", pinId: 4})
.done(function(){DB.models.Photo.create({photoUrl: "http://blog.startle.com/wp-content/uploads/2013/07/SB-Maui-CreditRon-Dahlquist-Photography.jpg", pinId: 4})
.done(function(){DB.models.Pin.create({title: "DC", latitude: 38.9047, longitude: -77.0164, userId: 1, isRed: "f", description: "Yay DC"})
.done(function(){DB.models.Photo.create({photoUrl: "http://alumni.umich.edu/clubs/sites/default/files/uploads/washington_dc.jpg", pinId: 5})
.done(function(){DB.models.Photo.create({photoUrl: "https://gradcontent.com/lib/600x350/jefferson-memorial.jpg", pinId: 5})
.done(function(){DB.models.Photo.create({photoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Cherry_blossoms_in_Vancouver_3_crop.jpg", pinId: 5})
.done(function(){DB.models.Photo.create({photoUrl: "http://sultanaeducation.org/wp-content/uploads/2014/06/lincoln-memorial-picture.jpg", pinId: 5})
.done(function(){DB.models.Photo.create({photoUrl: "https://www.whitehouse.gov/sites/default/files/image/whitehouse_historypg.jpg", pinId: 5})
.done(function(){DB.models.Photo.create({photoUrl: "http://www.justrenttoown.com/blog/wp-content/uploads/2015/04/wdc.jpg", pinId: 5})
.done(function(){DB.models.Pin.create({title: "Tampa", latitude: 27.9681, longitude: -82.4764, userId: 1, isRed: "f", description: "Boo Tampa"})
.done(function(){DB.models.Photo.create({photoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/57/Downtown_Tampa_and_Convention_Center_During_Gasparilla_Pirate_Fest_2003.jpg", pinId: 6})
.done(function(){DB.models.Photo.create({photoUrl: "http://www.tampagov.net/sites/default/files/front/slideshow/TampaGov-Main-Image-16.jpg", pinId: 6})

.done(function(){process.exit();})

})})})})})})})})})})})})})})})})})})})})})})})})})})})})})})
